'use client'

import { useRef, useState } from 'react'

const W=1200,H=1200

export default function Home(){
 const input=useRef<HTMLInputElement>(null); const [src,setSrc]=useState(''); const [name,setName]=useState(''); const [role,setRole]=useState('Builder'); const [busy,setBusy]=useState(false)
 const load=async(file:File)=>{setBusy(true); try{let f=file;if(file.type==='image/heic'||file.type==='image/heif'){const m=await import('heic2any');const out=await m.default({blob:file,toType:'image/png'});f=new File([Array.isArray(out)?out[0]:out],'photo.png',{type:'image/png'})} setSrc(URL.createObjectURL(f))}finally{setBusy(false)}}
 const download=()=>{if(!src)return;const c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d')!;x.fillStyle='#f6f0df';x.fillRect(0,0,W,H);const img=new Image();img.onload=()=>{const s=Math.max(W/img.width,H/img.height);const w=img.width*s,h=img.height*s;x.save();x.beginPath();x.rect(80,80,1040,1040);x.clip();x.drawImage(img,600-w/2,600-h/2,w,h);x.restore();x.strokeStyle='#ff4d22';x.lineWidth=26;x.strokeRect(42,42,1116,1116);x.fillStyle='#102a43';x.font='900 62px Arial';x.fillText('HH GOA 2026',80,116);x.fillStyle='#ff4d22';x.font='900 34px Arial';x.fillText('HACK HORIZON',80,1100);x.fillStyle='#102a43';x.font='900 38px Arial';x.fillText(name||'BUILDER',80,1060);x.fillStyle='#f6f0df';x.fillRect(880,48,270,70);x.fillStyle='#102a43';x.font='900 30px Arial';x.fillText('#FrameInGoa',892,96);x.font='700 24px Arial';x.fillText(role.toUpperCase(),80,1025);c.toBlob(b=>{if(!b)return;const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='hh-goa-2026-frame.png';a.click()},'image/png')};img.src=src}
 const share=()=>{const text=encodeURIComponent(`I’m ready for HH Goa 2026 🚀 #FrameInGoa`);window.open(`https://twitter.com/intent/tweet?text=${text}`,'_blank')}
 return <main><header><span className="eyebrow">HACK HORIZON · GOA</span><h1>Frame your<br/><i>builder era.</i></h1><p>Upload a photo. Add your builder identity. Get a share-ready HH Goa 2026 frame in seconds.</p></header><section className="grid"><div className="panel"><label className="drop" onClick={()=>input.current?.click()}><input ref={input} type="file" accept="image/jpeg,image/png,image/heic,image/heif" hidden onChange={e=>e.target.files?.[0]&&load(e.target.files[0])}/>{src?<img src={src} alt="Preview"/>:<><strong>DROP YOUR PHOTO</strong><span>JPG · PNG · HEIC</span><em>{busy?'Processing…':'Tap to choose from your phone'}</em></>}</label><div className="fields"><input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Stack / role" value={role} onChange={e=>setRole(e.target.value)}/></div><button className="primary" disabled={!src} onClick={download}>↓ Download your frame</button><button className="secondary" disabled={!src} onClick={share}>𝕏 Share to X <small>#FrameInGoa</small></button></div><div className="preview"><div className="poster">{src?<img src={src} alt="Generated frame"/>:<div className="placeholder">YOUR<br/><b>PHOTO</b><br/>GOES HERE</div>}<div className="frame top">HH GOA 2026</div><div className="frame bottom"><b>{name||'BUILDER'}</b><span>{role.toUpperCase()}</span><i>#FrameInGoa</i></div></div></div></section><footer>No login. No signup. Just build, frame, share.</footer></main>
}